### ISSUE TITLE
Tiny Typo #1

### ISSUE THREAD

**Issue by TotoR115** [Gibberlings3/Murneth#5]
In `a#murn.d` there is a tiny typo:
https://github.com/Gibberlings3/Murneth/blob/47a2a2e9d8e6dfd896474e67e03a51dff9ab5ac6/mur'neth/dialogues/a%23murn.d#L74

Should be `GARRICK` instead of `GARRI`

**Comment by CamDawg** [comment]
Fixed in https://github.com/Gibberlings3/Murneth/commit/6848045d1169e6647ee98d0a6f686897fe9fc6fd
